-- Updates Liquid Site Tables to version 0.10 (from 0.9)

-- Update domain table columns
ALTER TABLE `LS_DOMAIN`
    DROP COLUMN `OPTIONS`,
    ADD COLUMN `CREATED` DATETIME NOT NULL DEFAULT '0000-00-00',
    ADD COLUMN `MODIFIED` DATETIME NOT NULL DEFAULT '0000-00-00';

-- Initialize domain table timestamps
CREATE TEMPORARY TABLE `LS_TEMP_1` AS
    SELECT DOMAIN, MIN(MODIFIED) CREATED
    FROM LS_CONTENT
    GROUP BY DOMAIN;
UPDATE `LS_DOMAIN`,`LS_TEMP_1`
    SET `LS_DOMAIN`.`CREATED` = `LS_TEMP_1`.CREATED,
        `LS_DOMAIN`.`MODIFIED` = NOW()
    WHERE `LS_DOMAIN`.`NAME` = `LS_TEMP_1`.`DOMAIN`;
DROP TABLE `LS_TEMP_1`;

-- Remove default values from domain table columns
ALTER TABLE `LS_DOMAIN`
    MODIFY COLUMN `CREATED` DATETIME NOT NULL,
    MODIFY COLUMN `MODIFIED` DATETIME NOT NULL;

-- Create new domain attribute table
CREATE TABLE `LS_DOMAIN_ATTRIBUTE` (
    `DOMAIN` VARCHAR(30) NOT NULL,
    `NAME` VARCHAR(200) NOT NULL,
    `DATA` MEDIUMTEXT NOT NULL,
    PRIMARY KEY (`DOMAIN`, `NAME`)
);

-- Remove unused user preference table
DROP TABLE `LS_PREFERENCE`;
