-- Updates Liquid Site Tables to version 0.4 (from 0.3)

-- Change domain length to 30 characters
ALTER TABLE `LS_DOMAIN`
    MODIFY COLUMN `NAME` VARCHAR(30) NOT NULL;
ALTER TABLE `LS_USER`
    MODIFY COLUMN `DOMAIN` VARCHAR(30) NOT NULL;
ALTER TABLE `LS_GROUP`
    MODIFY COLUMN `DOMAIN` VARCHAR(30) NOT NULL;
ALTER TABLE `LS_USER_GROUP`
    MODIFY COLUMN `DOMAIN` VARCHAR(30) NOT NULL;
ALTER TABLE `LS_HOST`
    MODIFY COLUMN `DOMAIN` VARCHAR(30) NOT NULL;
ALTER TABLE `LS_CONTENT`
    MODIFY COLUMN `DOMAIN` VARCHAR(30) NOT NULL;
ALTER TABLE `LS_ATTRIBUTE`
    MODIFY COLUMN `DOMAIN` VARCHAR(30) NOT NULL;
ALTER TABLE `LS_PERMISSION`
    MODIFY COLUMN `DOMAIN` VARCHAR(30) NOT NULL;
ALTER TABLE `LS_LOCK`
    MODIFY COLUMN `DOMAIN` VARCHAR(30) NOT NULL;


-- Add ENABLED column to LS_USER
ALTER TABLE `LS_USER`
    ADD COLUMN `ENABLED` SMALLINT NOT NULL;
UPDATE `LS_USER` SET `ENABLED` = 1;


-- Add table LS_PREFERENCE
CREATE TABLE `LS_PREFERENCE` (
    `DOMAIN` VARCHAR(30) NOT NULL,
    `USER` VARCHAR(30) NOT NULL,
    `NAME` VARCHAR(200) NOT NULL,
    `VALUE` VARCHAR(200) NOT NULL,
    PRIMARY KEY (`DOMAIN`, `USER`, `NAME`),
    INDEX `PREFERENCE_IDX1` (`DOMAIN`, `USER`)
);
